language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libxml2 libxml2-dev
  - gem install bundler
  - gem update --system
rvm:
  - 2.7.1
bundler_args: --without production
